name: End-to-End CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/my-cicd-project
            git pull origin main
            # The build and run commands
            docker build -t my-cicd-app .
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 80:80 my-cicd-app
